// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEUflYDFtvqo5fevn8e1EVk0UYy7dayAo',
    appId: '1:666506646890:web:122b79fc2e4dd478088113',
    messagingSenderId: '666506646890',
    projectId: 'gam-90491',
    authDomain: 'gam-90491.firebaseapp.com',
    storageBucket: 'gam-90491.firebasestorage.app',
    measurementId: 'G-GNZBSVVYVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrB_t4i6hWGYHwok7ORhKdamBSOMZ3tTI',
    appId: '1:666506646890:android:2d894f98eca3a47a088113',
    messagingSenderId: '666506646890',
    projectId: 'gam-90491',
    storageBucket: 'gam-90491.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhlazVTRqEjeMe-BMj8D38w8-hO8j2hWo',
    appId: '1:666506646890:ios:46b45620e0874977088113',
    messagingSenderId: '666506646890',
    projectId: 'gam-90491',
    storageBucket: 'gam-90491.firebasestorage.app',
    iosBundleId: 'com.example.gam',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhlazVTRqEjeMe-BMj8D38w8-hO8j2hWo',
    appId: '1:666506646890:ios:46b45620e0874977088113',
    messagingSenderId: '666506646890',
    projectId: 'gam-90491',
    storageBucket: 'gam-90491.firebasestorage.app',
    iosBundleId: 'com.example.gam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEUflYDFtvqo5fevn8e1EVk0UYy7dayAo',
    appId: '1:666506646890:web:622e1e209d4dac8c088113',
    messagingSenderId: '666506646890',
    projectId: 'gam-90491',
    authDomain: 'gam-90491.firebaseapp.com',
    storageBucket: 'gam-90491.firebasestorage.app',
    measurementId: 'G-8GPCLNDCDB',
  );
}
